<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net90</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

	

  <ItemGroup>
    <ProjectReference Include="..\0_Framework\0_Framework.csproj" />
    <ProjectReference Include="..\BasicDataManagement.Application.Contract\BasicDataManagement.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
