<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartManagement.Application.Contracts\PartManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\PartManagement.Domain\PartManagement.Domain.csproj" />
  </ItemGroup>

</Project>
